# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='category',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic',
        ),
    ]
