# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='exist',
            field=models.BooleanField(default=True, verbose_name='purpose is to trace the unexisting ones'),
        ),
        migrations.AddField(
            model_name='category',
            name='exist',
            field=models.BooleanField(default=True, verbose_name='purpose is to trace the unexisting ones'),
        ),
        migrations.AddField(
            model_name='product',
            name='exist',
            field=models.BooleanField(default=True, verbose_name='purpose is to trace the unexisting ones'),
        ),
    ]
