# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161004_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='category',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='product'),
        ),
    ]
